# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0008_auto_20170919_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmhash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/mainpage4.jpg', null=True, upload_to=''),
        ),
    ]
